repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: '^tests/data'
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        additional_dependencies: [".[colors]"]
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        additional_dependencies: ["Flake8-pyproject<2.0"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML"]
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
        files: "^pyproject.toml$"
