repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: '^tests/data'
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
        files: "^pyproject.toml$"
  - repo: local
    hooks:
      - id: black
        name: Format by black
        entry: poetry run black
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: isort
        name: Format by isort
        entry: poetry run isort
        args: ['--filter-files']
        language: system
        types_or: [cython, pyi, python]
        require_serial: true
      - id: flake8
        name: Lint by flake8
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true
      - id: mypy
        name: Lint by mypy
        entry: poetry run mypy
        language: system
        types_or: [python, pyi]
        require_serial: true
