name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: "${{ matrix.OS }}"
    strategy:
      matrix:
        OS: [ubuntu-22.04, macos-12, windows-2022]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      # Set up multiple python versions
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Use Python 3.9
        uses: actions/setup-python@v5
        id: cp39
        with:
          python-version: "3.9"
      - name: Install poetry
        run:  pipx install --python '${{ steps.cp39.outputs.python-path }}' "poetry<2.0"
      - run: poetry self add poetry-dynamic-versioning
      - name: Install dependencies
        run: poetry install --only dev
      - name: Test by tox
        run: poetry run tox --skip-missing-interpreters false
