name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: "${{ matrix.OS }}"
    strategy:
      matrix:
        OS: [ubuntu-22.04, macos-12, windows-2022]
        PYTHON: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Use Python ${{ matrix.PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.PYTHON }}"
      - name: Install poetry
        uses: snok/install-poetry@v1
      - run: poetry self add poetry-dynamic-versioning
      - name: Install dependencies
        run: poetry install --without lint
      - name: Test
        run: make test
  pyinstaller:
    runs-on: "${{ matrix.OS }}"
    strategy:
      matrix:
        OS: [ubuntu-22.04, windows-2022]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install pyinstaller
        run: pipx install pyinstaller && pipx inject pyinstaller .
      - run: pyinstaller ./bin/aws-clipper.py --onefile
      - name: Run executable
        run: ./dist/aws-clipper --version
