name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: "${{ matrix.OS }}"
    strategy:
      matrix:
        OS: [ubuntu-22.04, macos-12, windows-2022]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          # Set up multiple python versions
          python-version: |
            3.8
            3.10
            3.11
            3.9
      - name: Install poetry
        run:  pipx install --python '${{ steps.setup-python.outputs.python-path }}' "poetry<2.0"
      - run: poetry self add poetry-dynamic-versioning
      - name: Install dependencies
        run: poetry install --only dev
      - name: Test by tox
        run: poetry run tox --skip-missing-interpreters false
