name: Release

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install poetry plugins
        run: poetry self add poetry-dynamic-versioning
      - name: Build and publish
        run: |
          poetry config repositories.testpypi "$TESTPYPI_URL"
          poetry publish --build --repository testpypi
        env:
          TESTPYPI_URL: https://test.pypi.org/legacy/
          POETRY_PYPI_TOKEN_TESTPYPI: "${{ secrets.PYPI_TOKEN }}"
